// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type BlocksView = {
  /**
   * Content blocks
   */
  blocks?: Array<
    | {
        /**
         * Selected
         */
        _selected: "text";

        /**
         * Text
         */
        text: {
          /**
           * Title
           */
          title?: string;

          /**
           * Text
           */
          text?: string;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "images";

        /**
         * Images
         */
        images: {
          /**
           * Image
           */
          items: Array<{
            /**
             * Image
             */
            imageId: string;

            /**
             * Description of the image for visually impaired users (alt text)
             */
            altText: string;

            /**
             * Caption
             */
            caption?: string;
          }>;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "factbox";

        /**
         * Factbox
         */
        factbox: {
          /**
           * Title
           */
          title?: string;

          /**
           * Text
           */
          text: string;

          /**
           * Theme
           */
          theme?: string;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "accordion";

        /**
         * Accordion
         */
        accordion: {
          /**
           * Title
           */
          title?: string;

          /**
           * Accordion element
           */
          items: Array<{
            /**
             * Title
             */
            title: string;

            /**
             * Text
             */
            text: string;
          }>;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "cards";

        /**
         * Cards
         */
        cards: {
          /**
           * Image
           */
          title?: string;

          /**
           * Theme
           */
          theme?: string;

          /**
           * Image placement
           */
          imagePosition: "top" | "bottom" | "left" | "right";

          /**
           * Cards
           */
          items: Array<{

            link:
              | {
                  /**
                   * Selected
                   */
                  _selected: "internal";

                  /**
                   * Internal
                   */
                  internal: {
                    /**
                     * Internal link
                     */
                    internalLink: string;
                  };
                }
              | {
                  /**
                   * Selected
                   */
                  _selected: "external";

                  /**
                   * External
                   */
                  external: {
                    /**
                     * External link
                     */
                    externalLink: string;
                  };
                };

            /**
             * Kicker
             */
            kicker?: string;

            /**
             * Overwrite title
             */
            title?: string;

            /**
             * Text
             */
            text?: string;

            /**
             * Image
             */
            imageId?: string;
          }>;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "reuse";

        /**
         * Reuse
         */
        reuse: {
          /**
           * Include blocks from this content
           */
          contentId: string;
        };
      }
  >;

  /**
   * Block title
   */
  blockTitle?: string;

  /**
   * Vertical spacing
   */
  gapRow: "lg" | "md" | "sm" | "none";
}
