// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type BlocksConfig = {
  /**
   * Vertical spacing
   */
  gapRow?: "sm" | "md" | "lg" | "xl" | "xxl" | "none";

  /**
   * Block layout
   */
  blockLayout?: "normal" | "frontpage";
};
