// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type BlocksMap = {
  /**
   * Center
   */
  center: string;

  /**
   * Zoom
   */
  zoom: number;

  /**
   * Markers
   */
  markers?: Array<
    | {
        /**
         * Selected
         */
        _selected: "popup";

        /**
         * Popup
         */
        popup: {
          /**
           * Position
           */
          lngLat: string;

          /**
           * Text
           */
          text?: string;
        };
      }
  >;
};
