// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type BlocksView = import("./blocks-view").BlocksView;

declare global {
  interface XpPartMap {
    "blocks:blocks-view": BlocksView;
  }
}
