// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type BlocksCards = {
  /**
   * Image
   */
  title?: string;

  /**
   * Cards
   */
  items: Array<{

    link:
      | {
          /**
           * Selected
           */
          _selected: "internal";

          /**
           * Internal
           */
          internal: {
            /**
             * Internal link
             */
            internalLink: string;
          };
        }
      | {
          /**
           * Selected
           */
          _selected: "external";

          /**
           * External
           */
          external: {
            /**
             * External link
             */
            externalLink: string;
          };
        };

    /**
     * Overwrite title
     */
    title?: string;

    /**
     * Intro
     */
    intro?: string;

    /**
     * Image
     */
    imageId?: string;

    /**
     * Image placement
     */
    imagePosition: "top" | "bottom" | "left" | "right";
  }>;
}
